# These are used for Apache symlinks for access to images using http
- name: build_images | Ensuring Image Folders Exist For Apache
  file:
    path: "{{ tftpserver_tftpboot_dir }}/{{ item }}"
    state: "directory"
  with_items: '{{ tftpserver_apache_links }}'
  when: tftpserver_apache_links is defined

- name: build_images | Downloading ISOs
  get_url:
    url: "{{ item.url }}/{{ item.file }}"
    dest: "{{ tftpserver_tftpboot_dir }}/images/{{ item.file }}"
    force: no
  with_items: '{{ tftpserver_iso_images }}'
  when: tftpserver_iso_images is defined

- name: build_images | Creating Image Folders
  file:
    path: "{{ tftpserver_tftpboot_dir }}/images/{{ item }}"
    state: "directory"
  with_items: '{{ tftpserver_images_folders }}'
  when: tftpserver_images_folders is defined

- name: build_images | Unmounting ISO Images
  mount:
    name: "{{ tftpserver_tftpboot_dir }}/images/{{ item.folder }}"
    src: "{{ tftpserver_tftpboot_dir }}/images/{{ item.file }}"
    fstype: "iso9660"
    state: "unmounted"
  with_items: '{{ tftpserver_iso_images }}'
  when: tftpserver_iso_images is defined

- name: build_images | Setting {{ tftpserver_tftpboot_dir }} Folder Permissions
  file:
    path: "{{ tftpserver_tftpboot_dir }}"
    state: "directory"
    recurse: yes
    owner: "nobody"
    group: "nogroup"

- name: build_images | Mounting ISO Images
  mount:
    name: "{{ tftpserver_tftpboot_dir }}/images/{{ item.folder }}"
    src: "{{ tftpserver_tftpboot_dir }}/images/{{ item.file }}"
    fstype: "iso9660"
    state: "mounted"
  with_items: '{{ tftpserver_iso_images }}'
  when: tftpserver_iso_images is defined

- name: build_images | Configuring Apache2 Links
  file:
    src: "{{ tftpserver_tftpboot_dir }}/{{ item }}"
    dest: "{{ tftpserver_apache_root }}/{{ item }}"
    owner: "www-data"
    group: "www-data"
    state: "link"
  with_items: '{{ tftpserver_apache_links }}'
  when: tftpserver_apache_links is defined

- name: build_images | Setting Apache2 Folder Permissions
  file:
  path: "{{ tftpserver_apache_root }}"
  state: "directory"
  recurse: yes
  owner: "www-data"
  group: "www-data"
  mode: "0755"
  when: tftpserver_apache_links is defined
