---
# tasks file for sorensj.tftp

- include: debian.yml
  when: ansible_os_family == "Debian"

- include: config_tftp.yml
  when: tftpserver_config_tftp

- include: build_images.yml
  when: tftpserver_build_images
