---
# tasks file for sorensj.tftp

- name: Install TFTPD-HPA package
  ansible.builtin.include_tasks: install_tftp.yml
  when: tftpserver_install_tftp

- name: Build images on TFTP Server
  ansible.builtin.include_tasks: build_images.yml
  when: tftpserver_build_images
